export interface ImageConfig {
  href: string;
  name: string;
  type: number;
  prompt: string;
}

export const imageConfigs: ImageConfig[] = [
  { href: "/demo1.jpeg", name: "Cartoon", type: 1, prompt: 'Based on the core subject (character/scene/object) of the user-uploaded image, generate a Japanese hand-drawn anime-style image. Key requirements: ① Clear black outlines with thickness adjusting to structural layers; ② Flat coloring as the main tone, plus soft gradient shadows locally (no realistic light transitions); ③ For characters: 2D anime facial features (large eyes, simplified nose, plump lips) and fluffy hairstyles; ④ Backgrounds can include anime elements (halftone texture, hand-drawn details, simplified layers); overall style aligns with Demon Slayer or Your Name, and keeps the original subject’s shape and core elements.' },
  { href: "/demo2.jpeg", name: "Cyberpunk", type: 2, prompt: 'Based on the core subject (character/scene/object) of the user-uploaded image, generate a cyberpunk-style image. Key requirements: ① Use high-saturation neon (pink, electric blue, fluorescent purple) with dark black/gray bases for sharp light-dark contrast, plus neon glows and light pollution; ② Add cyberpunk elements: rainy wet streets, holographic ads, stacked shabby buildings, tangled metal pipes; ③ For characters: cybernetic prosthetics, futuristic clothing (glowing patterns, leather/metal). For objects: retro-tech textures (e.g., CRT screens, exposed circuits); ④ Style matches Blade Runner 2049/Cyberpunk 2077—retain the original subject’s core shape/function, infuse cyberpunk’s "high-tech + dilapidation" essence.' },
  { href: "/demo3.jpeg", name: "CG", type: 3, prompt: 'Based on the core subject (character/scene/object) of the user-uploaded image, generate a film-grade game CG-style image. Key requirements: ① Detail precision meets industry CG standards (e.g., character hair rendered at individual strand level, micro-textures on objects, rich scene depth); ② Film-level lighting (key light + fill light + rim light, strong light-dark contrast, highlights with metal/glass reflections); ③ High-saturation colors + film grading (slight film grain allowed, no flat coloring); ④ Overall style matches Final Fantasy game CG or Disney’s Frozen, combining 3D dimensionality and film narrative feel; keep the original subject’s movements, atmosphere, and functions intact.' },
  { href: "/demo4.jpeg", name: "Pixel", type: 4, prompt: 'Based on the core subject (character/scene/object) of the user-uploaded image, generate a pixel-style image. Key requirements: ① Compose the image with clear pixel blocks, resolution matching retro pixel aesthetics (e.g., 8-bit/16-bit), retaining pixel granularity; ② Use high-saturation retro colors (mainly red/blue/yellow) or low-saturation nostalgic colors, no gradient transitions; ③ Simplify the subject’s outline, present details with pixels (e.g., character features, object textures); ④ Add pixel-style elements (pixelated clouds, block plants, retro game UI), overall matching Stardew Valley/Terraria visuals, retaining the original subject’s core shape and function.' },
  { href: "/demo5.jpeg", name: "Colored Pencil", type: 5, prompt: 'Based on the core subject (character/scene/object) of the user-uploaded image, generate a colored pencil-style image. Key requirements: ① Highlight colored pencil stroke textures, natural lines (no stiffness), colors with slight stroke overlay; ② Use soft low-saturation colors, present light-dark transitions via color layering, no bright blocks; ③ Outline subject details with fine colored pencil lines (e.g., character hair strands, object textures), light background blending; ④ Overall matching hand-drawn colored pencil texture, similar to paper-based colored pencil works, retaining the original subject’s core shape and atmosphere.' },
  {
    href: "/demo6.jpeg", name: "Old Photo Reader", type: 6, prompt: `Professional old photo restoration for the provided image (B&W/color, add era if known), key requirements:
For color photos: Fix yellowing/fading/color cast per original tone, keep natural skin tones;
Remove scratches/creases/mold/noise, retain original paper/film texture;
Boost resolution to 300dpi+ at original aspect ratio, enhance sharpness of blurry areas, preserve layering;
Fill in damages/missing parts logically per scene, no visible seams;
Keep era features (e.g., B&W contrast, vintage vignetting) without losing historical texture.` },
  {
    href: "/demo7.jpeg", name: "1-Inch", type: 7, prompt: `Based on the provided image, generate a 1-inch ID photo with a blue background that meets official ID photo standards, strictly complying with the following 4 requirements:
1. **Size Specifications**：Physical size of 2.5cm × 3.5cm, resolution ≥ 300dpi (to ensure high-definition printing without blurriness), accurate aspect ratio, no stretching/cropping distortion;
2. **Background Requirements**：Solid blue background (color reference #0066CC), no noise, gradients, shadows or textures, with clear boundaries between the background edge and the person’s outline;
3. **Portrait Shooting Standards**：The person is photographed front-facing, with the head accounting for 1/2 of the frame, looking straight at the camera with a natural expression (no exaggerated movements/expressions); formal clothing or light-colored tops are recommended (to avoid blending with the blue background);
4. **Image Quality Adaptation**：No noise or grain in the image, even exposure on the person’s face (no local overexposure/underexposure), no obstructions (e.g., hair covering eyes/eyebrows, accessories blocking the face), suitable for official scenarios such as ID cards, resumes, and visas.` },

];